spring:
  rabbitmq:
    host: 39.104.94.151
    port: 5675
    virtual-host: /zhouyang
    username: zhouyang
    password: zhouyang
    # 开启消息确认机制 confirm 异步
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual # 手动确认
        prefetch: 1 # 每次消费一条消息
  application:
    name: consumer-rabbitmq
server:
  port: 8082