server:
  port: 8009
#应用服务名
spring:
  application:
    name: gateway
  cloud:
    #配置nacos注册中心地址
    nacos:
      discovery:
        server-addr: http://39.104.94.151:7848
        namespace: 18bab497-6ecb-42c1-9a7c-e9c7dadc554d
    #配置网关路由
    gateway:
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
        #user-1
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path= /user/**

