server:
  port: 8010
#应用服务名
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: http://localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public