server:
  port: 8009
#应用服务名
spring:
  application:
    name: loadBalancer
  cloud:
    #配置nacos注册中心地址
    nacos:
      discovery:
        server-addr: http://39.104.94.151:7848
        namespace: 18bab497-6ecb-42c1-9a7c-e9c7dadc554d
    #关闭ribbon的负载均衡
    loadbalancer:
      ribbon:
        enabled: false