server:
  port: 8020
#应用服务名
spring:
  application:
    name: order-service
  cloud:
    #配置nacos注册中心地址
    nacos:
      discovery:
        server-addr: http://39.104.94.151:7848
        namespace: 18bab497-6ecb-42c1-9a7c-e9c7dadc554d
#配置springboot 的日志级别 ，保证openFeign 的日志级别 和springboot 一致 都是debug，也可以全局配置， 也可以单独配置，这里单独配置 为了方便查看 openFeign 的日志
logging:
  level:
    com.zhouyang.springcloud.order.feign: debug #单独配置openFeign 的日志级别
#配置openFeign 的日志级别
feign:
  client:
    config:
      order-service: #服务名
        connect-timeout: 5000 #连接超时时间
        read-timeout: 5000 #读取超时时间
        loggerLevel: full #配置openFeign 的日志级别
        contract: feign.Contract.Default #配置openFeign 的契约为默认的契约
        request-interceptors[0]: #配置openFeign 的拦截器
          - com.zhouyang.springcloud.order.interceptor.feign.AuthFeignInterceptor #配置openFeign 的拦截器